---
- name: Install zabbix agent
  hosts: all
  become: yes

  pre_tasks:

    - name: Open ferewall
      shell: |
        iptables -I FORWARD -s {{ ansible_default_ipv4.address }} ! -d 192.168.0.0/16 -p tcp -j ACCEPT
        iptables -I FORWARD -d {{ ansible_default_ipv4.address }} ! -s 192.168.0.0/16 -p tcp -j ACCEPT

        iptables -I FORWARD -s {{ ansible_default_ipv4.address }} ! -d 192.168.0.0/16 -p udp -j ACCEPT
        iptables -I FORWARD -d {{ ansible_default_ipv4.address }} ! -s 192.168.0.0/16 -p udp -j ACCEPT

        iptables -I FORWARD -s {{ ansible_default_ipv4.address }} ! -d 192.168.0.0/16 -p icmp -j ACCEPT
        iptables -I FORWARD -d {{ ansible_default_ipv4.address }} ! -s 192.168.0.0/16 -p icmp -j ACCEPT
      delegate_to: gateway
      ignore_errors: yes

  tasks:

    # - debug:
    #     var: ansible_default_ipv4.address

    # - pause:
    #     prompt: "Continue ?"
    #     echo: no
    
  roles:
     - role: dj-wasabi.zabbix-agent
  ignore_errors: yes

  post_tasks:
    
    - name: Close ferewall
      shell: |
        iptables -D FORWARD -s {{ ansible_default_ipv4.address }} ! -d 192.168.0.0/16 -p tcp -j ACCEPT
        iptables -D FORWARD -d {{ ansible_default_ipv4.address }} ! -s 192.168.0.0/16 -p tcp -j ACCEPT
        
        iptables -D FORWARD -s {{ ansible_default_ipv4.address }} ! -d 192.168.0.0/16 -p udp -j ACCEPT
        iptables -D FORWARD -d {{ ansible_default_ipv4.address }} ! -s 192.168.0.0/16 -p udp -j ACCEPT

        iptables -D FORWARD -s {{ ansible_default_ipv4.address }} ! -d 192.168.0.0/16 -p icmp -j ACCEPT
        iptables -D FORWARD -d {{ ansible_default_ipv4.address }} ! -s 192.168.0.0/16 -p icmp -j ACCEPT
      delegate_to: gateway
      ignore_errors: yes
